[general]
theme = "default"
debug = true
first_run = false

[display]
invert = true
driver = "only_web"

[display_cast]
default = true
streaming = "ffmpeg"

[network]
interface = "vEthernet (vlan )"
ask_interface = false

[bluetooth]
interface = "Conexin de red Bluetooth"
ask_interface = false

[plugins]
enabled = true
folder = "./plugins"
