[general]
theme = "default"
debug = true
first_run = false

[display]
invert = true
driver = "st7735S"
timeout = 10

[display_cast]
default = false
streaming = "ffmpeg"

[network]
interface = "vEthernet (vlan )"
ask_interface = false

[bluetooth]
interface = "Conexin de red Bluetooth"
ask_interface = false

[pheripherals]
enable_keyboard = true
enable_pins = false
enable_web = false


[plugins]
enabled = true
folder = "./plugins"
