[app]
name = "IR Tools"
version = "1.0"
description = "Herramientas basicas para interactuar con senales Infrarrojas (IR)."
author = "PiPerW"
category = "IR"

[requirements]
apt = []
pip = []
github = ["https://github.com/probonopd/irdb"]
